language: node_js
node_js:
  - "7"
  - "6"
  - "5"
  - "4"
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info
before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi

install:
  - npm install
